spring:
    application:
       name: Meme-Website
    data:
       redis:
           host: ${REDIS_HOST}
           port: ${REDIS_PORT}
           password: ${REDIS_PASSWORD}
       mongodb:
           uri: ${MONGODB_URI}
           database: ${MONGODB_DATABASE}
           auto-index-creation: true
    mail:
       host: ${MAIL_HOST}
       port: ${MAIL_PORT}
       username: ${MAIL_USERNAME}
       password: ${MAIL_PASSWORD}
       properties:
           mail:
               smtp:
                   auth: true
                   starttls:
                       enable: true
                       required: true

    servlet:
        multipart:
            max-file-size: 15MB
            max-request-size: 15MB

server:
   port: ${PORT:8080}

jwt:
    secret: ${SECURITY_SECRET_KEY}



logging:
   level:
       root: INFO

frontend:
   url: ${FRONTEND_URL}
   websocket:
        url: ${FRONTEND_WEBSOCKET_URL}

aws:
    region: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    credentials:
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}

rate-limiting:
  limits:
    api:
      auth:
        maxTokens: 10
        refillRatePerSec: 0.1
      token:
        maxTokens: 5
        refillRatePerSec: 0.05
      upload:
        maxTokens: 3
        refillRatePerSec: 0.01
      write:
        maxTokens: 10
        refillRatePerSec: 1
      delete:
        maxTokens: 5
        refillRatePerSec: 0.1
      read:
        maxTokens: 30
        refillRatePerSec: 1
      scroll:
        maxTokens: 60
        refillRatePerSec: 2
    ws:
      comment:
        maxTokens: 20
        refillRatePerSec: 2
      like:
        maxTokens: 50
        refillRatePerSec: 10
      save:
        maxTokens: 10
        refillRatePerSec: 2
      follow:
        maxTokens: 5
        refillRatePerSec: 0.5
      session:
        maxTokens: 20
        refillRatePerSec: 1